## Example config file, i.e., the argument to the '--config' option in...
##
##   $ threadfin reconcile --config my-config.yaml main chase
##
## ...and similar commands.

# TBD: Document templates, once we understand them.
template_dir: 'XX_OTS_BOOKKEEPING_DIR_XX/threadfin/reconcile/templates'

# 'accounts' is a list of dictionaries.  The keys and values in each
# dictionary are as follows:
#
#     key            value
#   --------------   ------------------------------------------------
#   'name':          (string)  A short name by which to identify a
#                              particular beancount file.
#    
#   'ledger_file':   (string)  Path to the corresponding beancount
#                              file. 
#
# When using ots-bookkeeping commands, you will identify beancount
# files with the names defined here, not with the files' paths.
# The examples below just have the paths to our sample data; you
# should edit the name values and path values as necessary for your
# purposes, of course.
accounts: [
{         'name':  'main',
   'ledger_file':  'XX_OTS_BOOKKEEPING_DIR_XX/threadfin/examples/generic_samples/main.beancount',
},

{         'name':  'chase',
   'ledger_file':  'XX_OTS_BOOKKEEPING_DIR_XX/threadfin/examples/generic_samples/chase.beancount',
},
]

# This dictionary is used in reconcilation.  
# 
# The keys are the short names that identify beancount files, i.e.,
# each key must be a name value from the 'accounts' element described
# earlier.
# 
# The values are lists saying which accounts to reconcile.  Most
# likely, the values lists will be identical.  TBD: what happens if
# they're not?  I don't know.  Experiments/patches welcome.
# 
# If you're using the sample data, the two entries for 'chase' and
# 'main' below will work.
reconcile: [
{
   'chase':  ['Liabilities:US:Chase:Slate'],
    'main':  ['Liabilities:US:Chase:Slate']
}
]
